--TODO: Use Sets
GLOBAL_CHANNEL = 1

GLOBAL_MSG_ORIGIN = "origin"
GLOBAL_MSG_SET_SAFE_POS_START = "setSafeStart"
GLOBAL_MSG_SET_SAFE_POS_END = "setSafeEnd"
GLOBAL_MESSAGES = {}
GLOBAL_MESSAGES[GLOBAL_MSG_ORIGIN] = true
GLOBAL_MESSAGES[GLOBAL_MSG_SET_SAFE_POS_START] = true
GLOBAL_MESSAGES[GLOBAL_MSG_SET_SAFE_POS_END] = true

COMMAND_CHANNEL = 9000
COMMAND_MSG_STOP = "stop"
COMMAND_MESSAGES = {}
COMMAND_MESSAGES[COMMAND_MSG_STOP] = true