--TODO: Use Sets
GLOBAL_CHANNEL = 1
POCKET_CHANNEL = 1000

GLOBAL_MSG_ORIGIN = "origin"
GLOBAL_MSG_SET_SAFE_START = "setSafeStart"
GLOBAL_MSG_SET_SAFE_END = "setSafeEnd"
GLOBAL_MSG_GET_SAFE_START = "getSafeStart"
GLOBAL_MSG_GET_SAFE_END = "getSafeEnd"

GLOBAL_MESSAGES = {
	[GLOBAL_MSG_ORIGIN] = true,
	[GLOBAL_MSG_SET_SAFE_START] = true,
	[GLOBAL_MSG_SET_SAFE_END] = true,
	[GLOBAL_MSG_GET_SAFE_START] = true,
	[GLOBAL_MSG_GET_SAFE_END] = true
}

COMMAND_CHANNEL = 9000
COMMAND_MSG_STOP = "stop"
COMMAND_MESSAGES = {
	[COMMAND_MSG_STOP] = true
}

WORLD_FILE = "ws/data/world.txt"